### ISSUE TITLE
Failed to find `autodoc.config.json` file. (first time running doc index)

### ISSUE THREAD

**Issue by shi-yan** [context-labs/autodoc#1]
running doc index for the first time gave:

Failed to find `autodoc.config.json` file. Are you in the right directory?
[Error: ENOENT: no such file or directory, open './autodoc.config.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './autodoc.config.json'
}

**Comment by samheutmaker** [comment]
Hey sorry this project wasn't totally supposed to get launched yet! You can fix your issue by running running `doc init` before `doc index`. I'm about to push a change to do this automatically :)
