### ISSUE TITLE
Error: this.callbackManager.handleLLMError is not a function

### ISSUE THREAD

**Issue by Arielegend** [context-labs/autodoc#15]
After successfully indexing my repo, I keep getting error message 
 "this.callbackManager.handleLLMError is not a function"
 
 what can I do ?

**Comment by samheutmaker** [comment]
This means your call to OpenAI is failing for some reason. We don't currently surface the underlying error. I'll push a change that throws the underlying error later today.

**Comment by Arielegend** [comment]
Cool.
My workaround it is to reInstall AutoDoc.

However, I have a question,
If I successfuly indexed a repo,
the I query it and all good,
then for some reason I get this error - 
what I do to fix it is to reInstall autoDoc.

My question is - DO I NEED TO RE-INDEX REPO?

**Comment by samheutmaker** [comment]
No, we'll fix this error. Do you have payment method associated with your OpenAI account?

**Comment by polto** [comment]
same here. after indexing I get this error on querying.

**Comment by Arielegend** [comment]
Fixed
Summarizing, for some reason it works under root and doesn't under a normal user

**Comment by polto** [comment]
I still have this error while trying to run `doc q`.

tried to install via npm or from source-code. still have the same error.
