### ISSUE TITLE
[Error: ENOENT: no such file or directory] while indexing

### ISSUE THREAD

**Issue by Bewinxed** [context-labs/autodoc#2]
I followed the steps to index my directory, which contains subfolders that also have git repos in them, but they are in the .gitignore file.

While running index, after 5 seconds i get this

```
Failed to find `autodoc.config.json` file. Did you run `doc init`?
[Error: ENOENT: no such file or directory, stat 'niftypay/mypython/bin/python'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'niftypay/mypython/bin/python'
}
```

not sure what's wrong, niftypay is a subdirectory and it's in .gitignore

**Comment by samheutmaker** [comment]
Autodoc does not read information from .gitignore. You can instead add the files you would like to ignore to the ignore array in the autodoc.config.js file.
