### ISSUE TITLE
Could be used to index documents like pdfs and talk to them ?

### ISSUE THREAD

**Issue by madruga8** [context-labs/autodoc#34]
Could be used to index documents like pdfs and talk to them ?

**Comment by dahifi** [comment]
Probably falls outside of the scope of this package. I've been using Obsidian on top of autodoc markdown files, there are a number of community plugins such as Smart Connections that will embed the docs, do semantic retrieval, and allow you to pass context to a chat. 

There's also a text-generator and AI commander plugins that can parse PDFs.

**Comment by madruga8** [comment]
Thanks
