### ISSUE TITLE
Thinking...Something went wrong: this.callbackManager.handleLLMError is not a function

### ISSUE THREAD

**Issue by droc12** [context-labs/autodoc#39]
After executing doc q, I received an error message "Thinking...Something went wrong: this.callbackManager.handleLLMError is not a function", which was working fine before.

**Comment by tranqnhan** [comment]
I got a similar error when trying to test this tool out.
![image](https://github.com/context-labs/autodoc/assets/44640810/daf3cfcf-1493-4144-bfa7-0d98d2ea7f1a)

**Comment by prikumari1** [comment]
Create vector files...Error: ENOENT: no such file or directory, scandir '.autodoc\docs\markdown\
whether this autodoc only support for node repo or any lang?

**Comment by prikumari1** [comment]
i tried with autodoc repo as well  getting below error :

? How can I help with autodoc?
 How does traversal work in autodoc?
⠧ Thinking...Something went wrong: Request failed with status code 401
? How can I help with autodoc?
⠧ Thinking..

**Comment by prikumari1** [comment]
i am also facing this issue while i tried to get autodoc on .net project :

Error: Could not read directory: .autodoc\docs\markdown\. Did you run `sh download.sh`?
